language: java
jdk: oraclejdk8
before_install: echo "MAVEN_OPTS='-Xms128g -Xmx1g -XX:PermSize=128m -XX:MaxPermSize=256g'" > ~/.mavenrc

install:
  - echo 'cd releng/superParent' > .build.sh
  - echo 'mvn clean install -B -V 1> .build.stdout 2> .build.stderr' >> .build.sh
  - chmod 0755 .build.sh
script:
  - travis_wait 60 ./.build.sh
after_success: 
  - tail -n  200 .build.stdout
after_failure:
  - tail -n  300 .build.stderr
  - tail -n 2000 .build.stdout